egoist/poi

bin/vbuild-default.js, bin/vbuild-init.js, bin/vbuild-test.js, bin/vbuild.js, lib/addons.js, lib/index.js, lib/init.js, lib/test.js, lib/update-config.js, package.json, yarn.lock
This is a new command: `vbuild test` or `vbuild test [files] [options]`
This feature does no introduce any new dependencies, all those stuffs require to install locally in your project, by default it uses:
- 'Chrome', 'PhantomJS'
- 'mocha', 'chai'
- webpack 2.1.0-beta.22
So you need to install these if you use default options:
```json
{
"chai": "^3.5.0",
"karma": "^1.3.0",
"karma-chai": "^0.1.0",
"karma-chrome-launcher": "^2.0.0",
"karma-mocha": "^1.2.0",
"karma-phantomjs-launcher": "^1.0.2",
"karma-sourcemap-loader": "^0.3.7",
"karma-webpack": "^1.8.0",
"mocha": "^3.1.2",
"webpack": "2.1.0-beta.22"
}
```
=> Karma support

lib/index.js
When running vbuild in `--dev` with a custom port, it still checks the default port `4000` and barks, if somethings already running there. 
This lil commit changes the behaviour to have `--port`(or the `config.js` counterpart) take precedence over the default.
**Repro**
- fire something up on port 4000, ie: `python -mSimpleHTTPServer 4000`
- try to start vbuild on a custom port, ie: `vbuild --dev --port 3000`
**Expected**
vbuild just starts the dev server on port 3000 without warning/prompt
**Actual**
vbuild prompts `Something is already running on port 4000`
(but still starts the dev server on 3000)
=> take `--port` into account when detecting target port

lib/index.js
If I create a vue.config.js like this:
```javascript
const webpack = require('webpack')
module.exports = {
title: 'todo',
resolve: true,
open: false,
plugins: [
new webpack.DefinePlugin({
VERSION: '"1.2.3"'
})
]
}
```
It will fail to load config when webpack is not a dependency and vbuild is running globally as usual.
That's because it will raise a MODULE_NOT_FOUND error that is miss interpreted as config file not found, and nothing is printed.
This pull request try to fix that, but keep the default behavior to support .js and .json config files.
Please, let me know if I need to better explain myself
=> Stop ignoring errors inside vue.config

lib/test.js
When defining `inputFiles`, output was a Boolean
```js
options.inputFiles.length > 0 = Boolean
```
=> vbuild test inputFiles resulted in true

packages/poi-preset-typescript/index.js
This allows typescript to 'just work', without configuration from the user. 
Before in poi.config.js:
```
presets: [
require('poi-preset-typescript')({
// options are for ts-loader
appendTsSuffixTo: [/\.vue$/]
}),
],
config.module.rule('vue')
.use('vue')
.tap(vueOptions => {
vueOptions.esModule = true;
return vueOptions;
});
```
After:
```
presets: [
require('poi-preset-typescript')(),
],
```
They still need a definition file to allow importing .vue files inside of a .ts file though.
**src/sfc.d.ts:**
```
declare module "*.vue" {
import Vue from 'vue'
export default typeof Vue
}
```
=> fix: typescript files work without any extra config

packages/poi/lib/server.js
This is mainly to solve my need of passing the devServer header options to the webpack-dev-middleware instance.
=> Use compiler.options.devServer if present

packages/poi/lib/create-config.js, packages/poi/package.json
This issue is similar to the one encountered in the below issue.
https://github.com/chentsulin/electron-react-boilerplate/pull/245/files
In my particular case I was depending on a package which was using readable-stream.
https://github.com/nodejs/readable-stream/blob/master/lib/_stream_writable.js#L53
In the above snippet, you can see `process.browser` and `process.version`. When you define process in an object as was done previously it'll actually clobber all the `process` object normalization that webpack does. This means that packages like readable-stream essentially become unusable.
=> Fix issue with process object being clobbered

packages/poi/lib/create-config.js
Actually, you're overriding the default module resolution by not passing a relative 'node_modules' path.
This causes problems, for example, when you use `npm link` or `yarn link`. Packages won't be discovered for the linked modules.
This fixes it.
=> Use default module resolution

packages/poi/lib/server.js
Hey,
I think the docs about [proxying api requests](https://poi.js.org/#/home?id=proxy-api-request) are a bit misleading. They suggest a shorthand declaration as in [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware#shorthand) is possible. But no matter what URL is supplied it always proxies `/api`.
This little change actually allows this shorthand for URL.
=> Allow proxy shorthand other than '/api'

packages/poi-preset-karma/index.js
With a files config like this:
```
files: [
'test/*.test.js',
{pattern: 'test/*.m??', watched: false, included: false, served: true, nocache: false},
]
```
You would end up with a preprocessor array like this (see the 2nd key):
```
preprocessors:
{ 'test/*.test.js': [ 'webpack', 'sourcemap' ],
'[object Object]': [ 'webpack', 'sourcemap' ] },
```
This PR checks type and if object only includes if `included: false` (or absent)
=> karma-preset: Invalid path when using objects in files

packages/poi-preset-transform-test-files/index.js
On line 18, `input` is an array and so `input > 0` is always false. The fix checks the array length.
=> fix bug in preset-transform-test-files

packages/poi-preset-babel-minify/index.js
The babel-minify-preset always gets used, even when the `minimize` option is set to false.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/egoist/poi/256)
=> fix: make babel minify preset respect `minimize` option

packages/poi-preset-karma/README.md, packages/poi-preset-karma/index.js, packages/poi-preset-karma/package.json
Include the preset `poi-preset-typescript` _before_ this preset,
for example:
```
module.exports = {
presets: [
require('poi-preset-typescript')(),
require('poi-preset-karma')()
]
}
```
=> feat: poi-preset-karma supports TypeScript

packages/poi-preset-karma/index.js
The previous fix missed that when false it shouldn't create a key at all
so it ended up with a key named `[object Object]` nonetheless.
=> fix: Fixes preprocessors keys for when included === false

packages/poi-preset-karma/README.md, packages/poi-preset-karma/package.json
Karma by default loads all plugins starting with `karma- *`. This fix prevents the need to configure typescript in projects that do not use it.
=> make karma-typescript optional

packages/poi-preset-storybook/README.md, packages/poi-preset-storybook/lib/index.js, packages/poi-preset-storybook/package.json
For keeping it on track with latest default storybook config.
- [default loader](https://github.com/storybooks/storybook/blob/master/app/vue/src/server/config/webpack.config.js#L53)
- [genDefaultConfig](https://github.com/storybooks/storybook/blob/master/app/vue/src/server/config/defaults/webpack.config.js) stated in [here](https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode--default)
> Related to [!2](https://github.com/DrSensor/vue-authoring-template/issues/2).
Although its `webpack-chain` responsibility for documenting [`webpack.config.js` to `webpack-chain`](https://github.com/mozilla-neutrino/webpack-chain/issues/6#issuecomment-283851444) recipe. I think it would be nice if poi provides this to in the documentation.
=> Add markdown support on poi-preset-storybook

packages/plugin-storybook/lib/index.js
Fix #413 
It looks like they have changed their diet directory structure.
=> Fix storybook plugin

packages/dev-utils/hotDevClient.js
In my scenario, the page is being served by PHP and the URL to the bundle is pointed directly to the webpack dev server.
So, the website is being served at http://my-project.test and the script is pointing to http://localhost:8080/app.js.
By using window.location for the webpack dev server client, it is forcing the sockjs server to be on the same domain as the page. However, it's more accurate to get the dev server from the script.
References: 
* https://github.com/vuejs/vue-cli/pull/1421
* https://github.com/vuejs/vue-cli/issues/1390
* https://github.com/morrislaptop/VueServeValetDriver
=> Use URL of script instead of window.location for dev server

packages/poi/lib/plugins/develop.js
This patch makes protocol dynamic based on the dev server settings, instead of hardcoded as 'http'
=> fix(develop): use correct protocol in logs/open

packages/poi/lib/utils/getPublicPath.js
This PR updates the `getPublicPath` utility to return the configured `publicPath` during `watch` mode as well as the currently configured `build` mode.
My assumption on why `getPublicPath` exists is that when using the dev server via `poi develop`, assets are usually served from `/` instead of the configured asset path. For this reason, I have kept the `develop` command excluded from the list.
For anyone wishing to override the `publicPath` across all commands, they can use the `chainWebpack` hook to force update the configuration.
```js
chainWebpack(config, context) {
config.output.publicPath("/assets/");
}
```
This PR should somewhat resolve #460.
=> Use configured publicPath in watch

core/poi/lib/utils/validateConfig.js
- Allowed `devServer.hotEntries` to be a list of varying length
- Added `historyApiFallback` to enable custom routing for single-page apps
- Changed `open` to allow strings, as is allowed by `webpack-dev-server`
=> Improve devServer config validation

core/poi/lib/babel/preset.js, core/poi/lib/plugins/config-babel.js, core/poi/lib/utils/validateConfig.js, core/poi/package.json, other-packages/babel-plugin-assets-named-imports/__test__/index.test.js, other-packages/babel-plugin-assets-named-imports/index.js, other-packages/babel-plugin-assets-named-imports/package.json, test/kitchensink/package.json, test/kitchensink/src/features/webpack/AssetsNamedImports.test.js, test/kitchensink/src/features/webpack/assets/text.md, test/kitchensink/yarn.lock, yarn.lock
Convert specific named imports to corresponding webpack loader syntax:
```js
import logoUrl, { ReactComponent as Logo } from './logo.svg'
// 👇👇👇
import logoUrl from './logo.svg'
import Logo from '!svgr/webpack!./logo.svg'
```
=> Feature: named imports for assets

core/dev-utils/colors.js, core/dev-utils/formatWebpackMessages.js, core/dev-utils/openBrowser.js, core/dev-utils/package.json, core/dev-utils/prepareProxy.js, core/dev-utils/printServeMessage.js, yarn.lock
=> fix(dev-utils): refactor hotDevClient to ES5 compat

core/poi/lib/utils/validateConfig.js
It is now possible to specify optional `headers` object in `devServer` config.
=> Validate devServer.headers option

plugins/typescript/index.js
I am not sure if this fix should be merged, because it may break someone's config
=> fix(plugin-typescript): fix typo fork-ts-cheker -> fork-ts-checker

core/dev-utils/printServeMessage.js, core/poi/lib/plugins/serve.js, core/poi/lib/utils/validateConfig.js
fix #586
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#586: Keep `poi --serve` URLs and `output.publicUrl` Consistent](https://issuehunt.io/repos/56788834/issues/586)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>
=> Append `poi -s` output URLs with `output.publicUrl`

core/dev-utils/printServeMessage.js
Because it may make 404 errors.
Example:
1. Set `output.publicUrl = /admin/` (even `/admin`)
2. Visit `http://localhost:4000/admin` => Error: `Cannot GET /admin`
3. Visit `http://localhost:4000/admin/` => Ok
=> fix: keep the trailing slash of `output.publicUrl`

plugins/html-entry/lib/index.js
Closes #616
Fixed by marking JSON files with resource query `imported-from-html-entry` as normal js file.
=> fix json assets support in html entry

plugins/bundle-report/package.json, yarn.lock
Updating `webpack-bundle-analyzer` to address: https://www.npmjs.com/advisories/826
=> Update bundle-report dependencies

core/poi/lib/utils/validateConfig.js
accroding to this https://github.com/egoist/poi/blob/master/core/poi/lib/plugins/config-babel.js#L53-L54
regexp is allowed, AND regexp should be allowd like vue.config.js
but validations fail when regexp is passed
package manager like `cnpm` use symlink
like prettier module resolve to `node_modules/_prettier@1.19.1@prettier`
```
$ ll node_modules/prettier
lrwxr-xr-x  1 magicdawn  staff    25B 12  9 23:19 node_modules/prettier -> _prettier@1.19.1@prettier
```
regexp can be used to match this `/prettier/`
=> fix: add regexp to allowed type of options.transpileModules

plugins/typescript/README.md, plugins/typescript/index.js
This PR adds the ability to pass options to ts-checker directly from the plugin options.
Closes #675.
=> feat(plugin-typescript): add ts-checker options

plugins/typescript/index.js
It doesn't appear to be necessary -- for parallel builds,
happyPackMode will implicitly set it, but it can cause larger
output bundles as const enums aren't supported with that mode.
=> fix(typescript): Don't set `transpileOnly` in parallel mode

plugins/eslint/README.md, plugins/eslint/index.js
This PR enables `eslint-loader` to be additionally configured using `@poi/plugin-eslint` options. :tada:
/cc @dbettini
=> feat(eslint): Pass `loaderOptions` to `eslint-loader`

core/poi/lib/plugins/serve.js
Fixes #763 
I'm not sure how to write a test for this, but the fix worked locally
=> fix: With publicPath and historyApiFallback, manually set fallback index

core/poi/lib/babel/preset.js, core/poi/lib/plugins/config-react-refresh.js, core/poi/lib/utils/validateConfig.js
Remove React Refresh Babel plugin from Babel preset if `reactRefresh` option isn't set.
=> fix: make react refresh babel plugin optional
