egoist/poi

lib/index.js
see https://github.com/egoist/vbuild/issues/4
=> Loads vbuild.js if it exists

lib/update-config.js
=> Use modules instead of alias for added flexibility

lib/detect-free-port.js, lib/index.js, lib/terminal-utils.js, package.json, yarn.lock
Issue #22 
Done like in create-react-app
=> Prompt user to provide a new port if 4000 is already in use

package.json
=> chore(package): update detect-port to version 1.0.5

lib/update-config.js
If options.static is Array then just pass it directly to CopyWebpackPlugin.
like
`
static: [
{ from: 'static', to: './' },
{ from: 'config', to: './' },
]
`
=> Allow custom copy file

README.md
Added a comment for npm install explanation alogside yarn
=> Added comment for npm install

README.md
I use Poi for WhyVote.us and I really like it. Thanks for building Poi!
=> Add "WhyVote.us" to "Who is using Poi?"

README.md
=> Add Vuikit on Who is using POI list

packages/poi-preset-babili/README.md, packages/poi-preset-babili/example/App.vue, packages/poi-preset-babili/example/index.js, packages/poi-preset-babili/index.js, packages/poi-preset-babili/package.json
use babili instead of uglifyjs to minimize your js code.
=> Add babili preset

packages/poi-preset-elm/.gitignore, packages/poi-preset-elm/README.md, packages/poi-preset-elm/example/Main.elm, packages/poi-preset-elm/example/index.js, packages/poi-preset-elm/index.js, packages/poi-preset-elm/package.json
A language preset for Elm
* Hot reloading
* Option to turn on/off Elm debugger (aka time traveller)
* Includes working example
=> feat: Added Elm preset

packages/poi-preset-karma/README.md, packages/poi-preset-karma/index.js
=> Tweaks poi-preset-karma

packages/poi/lib/create-config.js
Avoid copying `.gitkeep` from static folder.
=> Ignore ".gitkeep" in static folder.

examples/component/Component.vue, examples/component/index.js, examples/component/package.json, packages/poi/lib/create-config.js, packages/poi/lib/handle-options.js, packages/poi/package.json, packages/poi/test/config.test.js
This is an attempt to resolve https://github.com/egoist/poi/issues/243
I tried to just follow what you outlined in the issue. Let me know what you think 😄
=> feat: adding support for --component flag

packages/poi/lib/handle-options.js
Thanks for the great tool! `<3`
=> Fix typo in PostCSS output message

packages/poi-preset-storybook/lib/index.js
https://github.com/egoist/poi/issues/319
Then maybe something like this?
> `../../` mean it will search `@storybook/vue` in `node_modules`
=> Support @storybook/vue and @storybook/react

packages/poi/lib/utils/loadEnv.js
Allow overriding .env file variables with a .local version
=> Adds support for .env*.local overrides

packages/poi/lib/plugins/config-base.js
Ref: [ChainedSet > add](https://github.com/neutrinojs/webpack-chain/blob/a60fc9f0f3c696a2f81c4cff77d265e572cb54c5/src/ChainedSet.js#L9)
=> fix: correct usage of resolve.extensions

plugins/bundle-report/README.md, plugins/bundle-report/index.js, plugins/bundle-report/package.json
Since you have showed intention to potentially add this plugin (https://github.com/egoist/poi/issues/507#issuecomment-449032295) here's the code that works with poi@12. I think it would be pretty useful for many projects that use poi.
=> Bundle report plugin

plugins/html-entry/lib/html-entry-loader.js
=> fix(html-entry): slash attrs for static assets

core/poi/lib/plugins/config-css.js, core/poi/package.json, yarn.lock
=> fix(dependency): update css-loader

create-poi-app/generator/saofile.js, create-poi-app/generator/templates/pwa/src/registerServiceWorker.js
=> feat(create-poi-app): add update notifier in pwa

core/poi/lib/index.js, core/poi/lib/plugins/config-babel.js, core/poi/lib/utils/validateConfig.js
=> feat: add babel.configFile, babel.babelrc options

core/poi/package.json, yarn.lock
=> Update copy-webpack-plugin to resolve potential security issue

core/poi/lib/babel/preset.js, core/poi/package.json, yarn.lock
=> feat: Add optional chaining support to default babel preset

core/poi/lib/babel/preset.js, core/poi/lib/plugins/config-react-refresh.js, core/poi/package.json, yarn.lock
=> feat(react): Add react-refresh support
